import { Poppins } from "next/font/google";
import "./custom.css";
import "./globals.css";
import "./main.css";
import StoreProvider from "@/lib/redux/StoreProvider";
import { Toaster } from "react-hot-toast";


const poppinsFront = Poppins({
  variable: "--poppins-font",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Home</title>
      </head>
      <body className={`${poppinsFront.variable} bg-white`}>
        <StoreProvider>
          {children}
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
