import { Poppins } from "next/font/google";
import "./custom.css";
import "./globals.css";
import "./main.css";
import { Toaster } from "react-hot-toast";
import StoreProvider from "@/Providers/StoreProvider";
import InitProvider from "@/Providers/InitProvider";
import ReactQueryProvider from "@/Providers/ReactQueryProvider";


const poppinsFront = Poppins({
  variable: "--poppins-font",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("first")
  return (
    <html lang="en" >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Home</title>
      </head>
      <body className={`${poppinsFront.variable} bg-white`}>
        <StoreProvider>
          <ReactQueryProvider>
            <InitProvider>
              {children}
              <Toaster />
            </InitProvider>
          </ReactQueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
